### ISSUE TITLE
Tailwind Plugin

### ISSUE THREAD

**Issue by Zegoverno** [Poimen/stencil-tailwind-plugin#6] opened 2021-09-01 22:03 UTC
I would like to experiment adding a tailwind plugin... I tried to follow the steps below and pass this new tailwind.config.js like in this example:

tailwind({
tailwindConf: tailwindConfig
}),

Install DaisyUI as Tailwind CSS plugin
(You need Node.js and Tailwind CSS installed.)

1. Install DaisyUI:
npm i daisyui
2. Then add DaisyUI to your tailwind.config.js
module.exports = {
    plugins: [
        require('daisyui'),
    ],
}
I couldn't get this working, any thoughts on how to do that? Many thanks

**Comment by Zegoverno** [comment] 2021-09-02 20:15
Hi, thank you for the suggestion, I could get it working, but only when setting shadow: false, with shadow: true I can't get the theme variables populated. Many thanks and have a nice week.

**Comment by Poimen** [comment] 2021-09-12 11:04
After some investigation, it looks like daisyui is using `:root` for style css variables. This approach is incomparable with web components. You would need to target `:host`. Not all tailwind libraries can be used directly because some selectors don't correlate. Tailwind itself is not designed for web components.

My suggestion is to use a global style sheet that pulls through the necessary variables as these will still work with the shadow dom. Otherwise there will be a bit of bloat with the shadow styles of unused variables.

Unfortunately my postcss patch doesn't work correctly so I wouldn't suggest trying that. I'm having a look into it but it doesn't work to put in a rename of root to host.

**Comment by Zegoverno** [comment] 2021-09-13 17:57
Do you think twind would help to fix this? Since it is just a compiler?

**Comment by Poimen** [comment] 2021-09-13 18:04
There are a couple of discussion threads for support but nothing has been confirmed yet. It is probably unlikely in the near term that web components will be supported.

**Comment by Poimen** [comment] 2021-12-23 10:21
In `v1.2.1` `postcss` plugins should be working now.

For daisyUI , you should be able to chain the `postcss-replace` plugin with `tailwind` plugin. An example of the configuration is:
```ts
// stencil.config.ts
// imports...

export const config: Config = {
  namespace: 'stencil-component-example',
  outputTargets: [
    // targets...
  ],
  plugins: [
    sass(),
    tailwind({
      tailwindConf,
      tailwindCssPath: './src/styles/tailwind.css',
      postcss: {
        plugins: [
          tailwindcss(),
          replace({ pattern: 'html', data: { replaceAll: ':host' } }),
          replace({ pattern: 'body', data: { replaceAll: ':host' } }),
          replace({ pattern: ':root', data: { replaceAll: ':host' } }),
          autoprefixer(),
        ]
      }
    }),
    tailwindHMR(),
  ]
};
```

HTH

@Zegoverno I'm closing this issue for now. Feel free to open another issue if there is something more.

**Closed by Poimen** 2021-12-23 10:21 UTC

**Comment by nedredmond** [comment] 2022-11-05 18:36
Just wanted to say thanks-- this works well!
